### ISSUE TITLE
Can't run the mod with 1.19.2

### ISSUE THREAD

**Issue by azzake** [TheBosoYolo/delay-packets#2]
When i tried to run this mod on 1.19.2 i get an error that this mod is only for 1.19.4, even on modrinth is writed that mod is for 1.19-1.19.4. Could you make this mod compatible for that version?

**Comment by AgentKosticka** [comment]
Yes, thank you for pointing out this issue. This error happened, because minecraft read that this mod is only suitable for 1.19.4, while in theory this mod is indeed compatible with 1.19.2 and lower. I have repackaged the mod and the updated version is now availible on modrinth
