### ISSUE TITLE
Update to 1.20+

### ISSUE THREAD

**Issue by lobsters1** [TheBosoYolo/delay-packets#3]
Hello, could you please update the mod to 1.20 and above? Would appreciate it. 😄

**Comment by AgentKosticka** [comment]
Hello! I have been working on a 1.20.x version, but as newer versions adds more packets to handle, it increases my work and the time it takes. The 1.20.x version could be finished next week by this time. For now check the updated version 1.1.0 [here](https://modrinth.com/mod/delay-packets/version/1.1.0+1.19.4) that added the compatibility for changing and saving settings, namely changing activation type (HOLD or TOGGLE) of all types (outgoing, incoming, block update, entity update) and the ability to disable chat feedback and fake player

**Comment by DearFox** [comment]
How is the update going?  I needed to check my server mod, and this seems to be the only mod that allows me to do this.
